import { useNavigate, useParams } from "react-router-dom";
import { ArrowLeft, ArrowRight, Download, Edit, Send } from "lucide-react";
import { PageHeader } from "@/components/shared/PageHeader";
import { Button } from "@/components/ui/button";
import { Section } from "@/components/shared/FormShell";
import { StatusBadge } from "@/components/shared/StatusBadge";
import { quotations } from "@/data/mock";
import { toast } from "sonner";

export default function QuotationPreview() {
  const { id } = useParams();
  const nav = useNavigate();
  const q = quotations.find((x) => x.id === id) ?? quotations[0];

  return (
    <div>
      <PageHeader title={q.id} description="Quotation preview" breadcrumbs={[{ label: "Quotations", to: "/quotations" }, { label: q.id }]}
        actions={<>
          <Button variant="outline" size="sm" onClick={() => nav(-1)}><ArrowLeft className="h-4 w-4 mr-1.5" />Back</Button>
          <Button variant="outline" size="sm"><Edit className="h-4 w-4 mr-1.5" />Edit</Button>
          <Button variant="outline" size="sm"><Download className="h-4 w-4 mr-1.5" />PDF</Button>
          <Button size="sm" onClick={() => { toast.success("Quotation sent to customer"); }}><Send className="h-4 w-4 mr-1.5" />Send</Button>
        </>}
      />
      <Section>
        <div className="max-w-3xl mx-auto">
          <div className="flex items-start justify-between pb-6 border-b border-border">
            <div>
              <div className="text-2xl font-bold">QUOTATION</div>
              <div className="text-sm text-muted-foreground mt-1">{q.id}</div>
            </div>
            <StatusBadge status={q.status} />
          </div>
          <div className="grid grid-cols-2 gap-8 py-6 border-b border-border">
            <div>
              <div className="text-xs text-muted-foreground uppercase tracking-wider mb-2">From</div>
              <div className="font-semibold text-sm">Acme Exports Ltd</div>
              <div className="text-sm text-muted-foreground mt-1">123 Marine Drive<br />Mumbai 400001, India<br />GST: 27ABCDE1234F1Z5</div>
            </div>
            <div>
              <div className="text-xs text-muted-foreground uppercase tracking-wider mb-2">To</div>
              <div className="font-semibold text-sm">{q.customer}</div>
              <div className="text-sm text-muted-foreground mt-1">Valid until: {q.validUntil}</div>
            </div>
          </div>
          <table className="w-full mt-6 text-sm">
            <thead className="border-b border-border">
              <tr><th className="text-left py-2 text-xs uppercase font-medium text-muted-foreground">Description</th><th className="text-right py-2 text-xs uppercase font-medium text-muted-foreground">Qty</th><th className="text-right py-2 text-xs uppercase font-medium text-muted-foreground">Price</th><th className="text-right py-2 text-xs uppercase font-medium text-muted-foreground">Total</th></tr>
            </thead>
            <tbody>
              {Array.from({ length: Math.min(q.items, 5) }).map((_, i) => (
                <tr key={i} className="border-b border-border">
                  <td className="py-3">Premium Cotton Fabric — Lot {i + 1}</td>
                  <td className="text-right py-3 tabular-nums">{200 + i * 50}</td>
                  <td className="text-right py-3 tabular-nums">$4.50</td>
                  <td className="text-right py-3 tabular-nums">${((200 + i * 50) * 4.5).toFixed(2)}</td>
                </tr>
              ))}
            </tbody>
          </table>
          <div className="mt-6 flex justify-end">
            <div className="w-64 space-y-1.5 text-sm">
              <div className="flex justify-between"><span className="text-muted-foreground">Subtotal</span><span className="tabular-nums">{q.currency} {(q.amount * 0.847).toLocaleString()}</span></div>
              <div className="flex justify-between"><span className="text-muted-foreground">Tax (18%)</span><span className="tabular-nums">{q.currency} {(q.amount * 0.153).toLocaleString()}</span></div>
              <div className="flex justify-between pt-2 border-t border-border font-semibold text-base"><span>Total</span><span className="tabular-nums">{q.currency} {q.amount.toLocaleString()}</span></div>
            </div>
          </div>
          <div className="mt-8 pt-6 border-t border-border flex items-center justify-between">
            <div className="text-xs text-muted-foreground">Generated by ExportOS · Acme Exports Ltd</div>
            <Button size="sm" onClick={() => nav("/quotations/convert")}>Convert to Order <ArrowRight className="h-3.5 w-3.5 ml-1" /></Button>
          </div>
        </div>
      </Section>
    </div>
  );
}
